name: sufenbao
description: sufenbao
version: 3.0.5+92

environment:
  sdk: ">=2.18.0 <=3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  #  flutter_qq_ads: ^2.5.0
  #  weibo_kit: ^4.0.0
  #  tencent_kit: ^5.0.2
  flutter_z_location: ^0.0.7
  qr_flutter: ^4.1.0
  image_gallery_saver: '^2.0.1'
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.1
  dio: ^4.0.6
  image_picker: ^0.8.7+2
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  json_serializable: ^6.5.3
  maixs_utils:
    path: package/maixs_utils
  settings_ui: ^2.0.2
  pinput: ^2.2.31
  awesome_dialog: ^3.0.2
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.10
  clipboard: ^0.1.3
  flutter_native_splash: ^2.2.12
  appcheck: ^1.0.6
  flutter_picker: ^2.1.0
  wechat_assets_picker: ^8.4.2
  wechat_camera_picker: ^3.7.0
  #  flutter_swiper: ^1.1.6
  flutter_swiper:
    path: package/flutter_swiper
  fluwx: ^3.12.2
  common_utils: 2.1.0
  keyboard_actions: ^4.0.1
  sticky_headers: ^0.3.0+2
  flutter_inappwebview: ^5.8.0
  url_launcher_platform_interface: ^2.1.2
  image_cropper: ^3.0.2
  animations: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_slidable: ^2.0.0
  package_info_plus: ^3.1.0
  jpush_flutter: ^2.4.9
  in_app_purchase: ^3.1.11
  sign_in_with_apple: ^4.3.0
  flutter_svg: ^2.0.5
  pay_ios: ^1.0.7
  permission_handler: ^10.4.5
  shake_animation_widget: ^3.0.3
  dotted_border: ^2.0.0+3
  flutter_pdfview: 1.2.9
  #屏幕适配
  flutter_screenutil: ^5.3.1
  animated_text_kit: ^4.2.2
  tobias:
    git:
      url: https://gitee.com/jacky4631/tobias.git
  flutter_alibc:
    git:
      url: https://gitee.com/jacky4631/flutter_alibc_kit.git
  flutter_ali_face_verify:
    git:
      url: https://gitee.com/jacky4631/flutter_ali_face_verify.git
  decimal: ^2.3.0

  chewie: ^1.4.0
  shimmer: ^2.0.0
  data_table_2: ^2.3.12
  shanyan:
    git:
      url: https://gitee.com/chuanglan253/CLShanYan_Flutter.git
      path: shanyan
      ref: v2.3.4.3
  signature: ^5.3.2
  encrypt: ^5.0.1
  connectivity_plus: ^3.0.6
  webview_flutter: ^4.2.1
  device_info_plus: ^8.2.0
  url_strategy: ^0.2.0
dev_dependencies:
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.12.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1024.png"
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/images/cash/
    - assets/images/share/
    - assets/images/mall/
    - assets/images/me/
    - assets/images/lv/
    - assets/images/menu/
    - assets/images/help/
    - assets/images/energy/
    - assets/key/
  fonts:
    - family: BaoIcons
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: headlinea
      fonts:
        - asset: assets/fonts/Alimama_ShuHeiTi_Bold.ttf

flutter_intl:
  enabled: true